artifact_types:
  - type_name: Architecture
    type_key: architecture
    id_prefix: ARCH
    id_format: '{prefix}-{number:3}'
    folder_path: docs/architecture
    attributes:
      - name: artifact_id
        type: string
        label: Artifact ID
        readonly: true
        required: true
      - name: title
        type: string
        label: Title
        required: true
        maxLength: 200
      - name: description
        type: text
        label: Description
        required: false
      - name: status
        type: enum
        label: Status
        default: draft
        options:
          - draft
          - review
          - approved
          - deprecated
      - name: priority
        type: enum
        label: Priority
        options:
          - low
          - medium
          - high
      - name: asil_level
        type: enum
        label: ASIL Level
        options:
          - QM
          - A
          - B
          - C
          - D
      - name: owner
        type: string
        label: Owner
      - name: tags
        type: array
        label: Tags
        itemType: string
      - name: plantuml_source
        type: text
        label: PlantUML Source
      - name: linked_requirements
        type: array
        label: Linked Requirements
        itemType: string
  - type_name: Feature
    type_key: feature
    id_prefix: FT
    id_format: '{prefix}-{number:3}'
    folder_path: docs/features
    attributes:
      - name: artifact_id
        type: string
        label: Artifact ID
        readonly: true
        required: true
      - name: title
        type: string
        label: Title
        required: true
        maxLength: 200
      - name: description
        type: text
        label: Description
        required: false
      - name: status
        type: enum
        label: Status
        default: draft
        options:
          - draft
          - review
          - approved
          - deprecated
      - name: priority
        type: enum
        label: Priority
        options:
          - low
          - medium
          - high
      - name: owner
        type: string
        label: Owner
      - name: tags
        type: array
        label: Tags
        itemType: string
  - type_name: Feature Requirement
    type_key: feature_requirement
    id_prefix: FEAT-REQ
    id_format: '{prefix}-{number:3}'
    folder_path: docs/features/requirements
    attributes:
      - name: artifact_id
        type: string
        label: Artifact ID
        readonly: true
        required: true
      - name: title
        type: string
        label: Title
        required: true
        maxLength: 200
      - name: description
        type: text
        label: Description
        required: false
      - name: status
        type: enum
        label: Status
        default: draft
        options:
          - draft
          - review
          - approved
          - deprecated
      - name: priority
        type: enum
        label: Priority
        options:
          - low
          - medium
          - high
      - name: asil_level
        type: enum
        label: ASIL Level
        options:
          - QM
          - A
          - B
          - C
          - D
      - name: owner
        type: string
        label: Owner
      - name: tags
        type: array
        label: Tags
        itemType: string
      - name: linked_requirements
        type: array
        label: Linked Requirements
        itemType: string
  - type_name: SW Requirement
    type_key: requirement
    id_prefix: REQ
    id_format: '{prefix}-{number:3}'
    folder_path: docs/requirements
    attributes:
      - name: artifact_id
        type: string
        label: Artifact ID
        readonly: true
        required: true
      - name: title
        type: string
        label: Title
        required: true
        maxLength: 200
      - name: description
        type: text
        label: Description
        required: false
      - name: status
        type: enum
        label: Status
        default: draft
        options:
          - draft
          - review
          - approved
          - deprecated
      - name: priority
        type: enum
        label: Priority
        options:
          - low
          - medium
          - high
      - name: asil_level
        type: enum
        label: ASIL Level
        options:
          - QM
          - A
          - B
          - C
          - D
      - name: owner
        type: string
        label: Owner
      - name: tags
        type: array
        label: Tags
        itemType: string
      - name: linked_requirements
        type: array
        label: Linked Requirements
        itemType: string
  - type_name: Test
    type_key: test
    id_prefix: TEST
    id_format: '{prefix}-{number:3}'
    folder_path: docs/tests
    attributes:
      - name: artifact_id
        type: string
        label: Artifact ID
        readonly: true
        required: true
      - name: title
        type: string
        label: Title
        required: true
        maxLength: 200
      - name: description
        type: text
        label: Description
        required: false
      - name: status
        type: enum
        label: Status
        default: draft
        options:
          - draft
          - review
          - approved
          - deprecated
      - name: priority
        type: enum
        label: Priority
        options:
          - low
          - medium
          - high
      - name: owner
        type: string
        label: Owner
      - name: tags
        type: array
        label: Tags
        itemType: string
      - name: linked_requirements
        type: array
        label: Linked Requirements
        itemType: string
      - name: linked_architecture
        type: array
        label: Linked Architecture
        itemType: string
